### ISSUE TITLE
Infinite Loops Encountered when Printing

### ISSUE THREAD

**Issue by LoganConnor** [PostRockRaven/Bomark_CSCI2270_FinalProject#3]
Hey guys, the project was easy to download and get going, and its an awesome idea! I encountered infinite loops a few times when printing, and it seems to always be after I have already made some function calls, suggesting that values are not being reset or something along those lines. If I can narrow down a more specific set of calls that leads to an infinite loop I will let you know. Button #7 seems especially problematic.

**Comment by PostRockRaven** [comment]
I looked at it, and I don't see problems with #7, but #5 will give an infinite loop after it is pressed once, anytime the option is chosen again it goes into an infinite loop but I can't figure out what's wrong with it

**Comment by PostRockRaven** [comment]
wait nvm i fix

**Comment by LoganConnor** [comment]
Great, I will close then.
